# Generated by Django 5.2.4 on 2025-08-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('password', models.CharField()),
                ('cpassword', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'User',
                'db_table': 'User',
            },
        ),
    ]
