# Generated by Django 5.2.4 on 2025-08-14 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsd', '0002_remove_user_cpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('mrp', models.IntegerField()),
                ('offprice', models.IntegerField()),
                ('rating', models.FloatField()),
                ('itemtype', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Product',
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appsd.user')),
                ('userquery', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Query',
                'db_table': 'Query',
            },
            bases=('appsd.user',),
        ),
    ]
