# Generated by Django 5.2.4 on 2025-08-16 04:47

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsd', '0003_product_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='thumbnail/default_thumbnail.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='thumbnail/'),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_data', to='appsd.product')),
            ],
            options={
                'db_table': 'ProductImages',
            },
        ),
    ]
