# Generated by Django 5.2.4 on 2025-08-16 04:52

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsd', '0004_product_thumbnail_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='thumbnail/'),
        ),
    ]
