# Generated by Django 5.2.4 on 2025-08-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsd', '0005_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product'},
        ),
    ]
