# Generated by Django 5.2.4 on 2025-08-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsd', '0006_alter_productimages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'ProductImages'},
        ),
    ]
