# Generated by Django 5.2.4 on 2025-08-16 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsd', '0007_alter_productimages_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
