# Generated by Django 5.2.4 on 2025-08-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsd', '0008_remove_product_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='Created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
