# Generated by Django 5.2.4 on 2025-08-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsd', '0009_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='Payment',
        ),
    ]
