# Generated by Django 5.2.4 on 2025-08-27 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsd', '0010_payment_user_id_alter_payment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appsd.user')),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Address',
                'db_table': 'Address',
            },
            bases=('appsd.user',),
        ),
    ]
