# Generated by Django 5.2.4 on 2025-08-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsd', '0011_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='query',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
