# Generated by Django 5.2.4 on 2025-08-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsd', '0013_address_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('userquery', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Query',
                'db_table': 'Query',
            },
        ),
    ]
